GISFproject/GISF/Claims/urls.py
from django.urls import path

from .views import CalimsRaiseView

app_name = 'Claim1'

urlpatterns = [
    path('RaiseClaim/', CalimsRaiseView, name='RaiseClaim')
]

GISFproject/GISF/GISF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('GISFAdmin/', include('GISFAdmin.urls')),
    path('Masters/', include('Masters.urls')),
    path('UnderWriter/', include('UnderWriter.urls')),
    path('Claims/', include('Claims.urls'))
]

GISFproject/GISF/GISFAdmin/urls.py
from django.urls import path

from .views import NewUserCreate, homepage, about, loginView, logout_view, register, mainmenu

app_name = 'MyAdmin'

urlpatterns = [
    path('registration/', NewUserCreate, name="NewUserCreate"),
    path('', homepage, name='homepage'),
    path('About/', about, name='About'),
    path('clogin/', loginView, name='clogin'),
    path('log-out/', logout_view, name='logout'),
    path("Newregister/", register, name="register"),
    path('mainmenu/', mainmenu, name='mainmenu'),
     ]

GISFproject/GISF/Masters/urls.py
from django.urls import path
from .views import ProductsMaster, ProductRisk, AgentCommision, createAgent, VehicleMasterView, \
    VehicleDepriciationMasterView, XxgenNcbMasterView, ClaimStatusMasterView, ClaimsSurveyorMasterView, \
    ClaimStatusListView

app_name = 'Masters'

urlpatterns = [
     path('ProductsMaster/', ProductsMaster, name='ProductsMaster'),
     path('ProductRisk/', ProductRisk, name='ProductRisk'),
     path('createAgent/', createAgent, name='createAgent'),
     path('AgentCommission/', AgentCommision, name='AgentCommission'),
     path('VehicleMaster/', VehicleMasterView, name='VehicleMaster'),
     path('VehicleDepreciation/', VehicleDepriciationMasterView, name='VehicleDepreciation'),
     path('NCBMaster/', XxgenNcbMasterView, name="NCBMaster"),
     path('Claimstatus/', ClaimStatusMasterView, name="Claimstatus"),
     path('Surveyormaster/', ClaimsSurveyorMasterView, name="Surveyormaster"),
     path('Claimslist/', ClaimStatusListView, name="ClaimStatusListView"),
    ]

GISFproject/GISF/UnderWriter/urls.py
from django.urls import path
from .views import InsuredcreateView, PolicyCreateView, PolicyUpdateView, PolicyBillsview

app_name = 'UnderWriter'

urlpatterns = [
    path('CreateInsured/', InsuredcreateView, name='CreateInsured'),
    path('PolicyCreate/', PolicyCreateView, name='PolicyCreate'),
    path('PolicyUpdate/', PolicyUpdateView, name='PolicyUpdate'),
    path('PolicyBillPay/', PolicyBillsview, name='PolicyBillPay'),
]

GISFproject/GISF/GISFAdmin/models.py
from django.db import models

# Create your models here.


class Users(models.Model):
    username = models.CharField(max_length=120)
    password = models.CharField(max_length=500)

    class Meta:
        db_table = 'Users'

GISFproject/GISF/GISFAdmin/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

from .PasswordManage import decrypt, encrypt
# from .forms import Userform
from .models import Users


# Create your views here.
def NewUserCreate(request):
    password = request.POST.get('pwd')
    username = request.POST.get('uid')
    if request.method == "POST":
        encr = encrypt(password,username)
        Users.objects.create(username=username, password=encr)
        dec = decrypt(encr, username)

    return render(request,'GISFAdminGISFAdmin/Registration.html')


def register(request):
    form = UserCreationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request = request,
                          template_name = "GISFAdmin/newuser.html",
                          context={"form":form})

    form = UserCreationForm
    return render(request = request,
                  template_name = "GISFAdmin/newuser.html",
                  context={"form":form})


def loginView(request):
    if request.method == 'GET':
        return render(request, 'GISFAdmin/login.html', {})
    else:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None :
            login(request, user)
            #return redirect('mainmenu/')
            return render(request, 'GISFAdmin/mainmenu.html', {})
        else:
            return render(request, 'GISFAdmin/login.html', {})


def logout_view(request):
    logout(request)
    return render(request, 'GISFAdmin/logout.html')


def homepage(request):
    return render(request, 'GISFAdmin/home.html')


def about(request):
    return render(request,'GISFAdmin/about.html')


def mainmenu(request):
    return render(request, 'GISFAdmin/mainmenu.html')

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/Registration.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    	{% csrf_token %}
        <input type="text" name="uid" value="">
        <input type="text" name="pwd" value="">
        <button class="submit-row" style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>
{% endblock %}

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/about.html
{% extends 'base.html' %}
{% block content %}

<h1>My General Insurance Product</h1>
<h2>Modules</h2>
<l1>
Underwriter <br>
Endorsement <br>
RE-INSURANCE <br>
RENEWALS <br>
CLAIMS <br>
Finance <br>
</l1>
<p1>General Insurance means to “Cover the risk of the financial loss from any natural calamities viz. Flood, Fire, Earthquake,
    Burglary, etc.. i.e. the events which are beyond the control of the owner of the goods for the things having insurable interest
    with the utmost good faith by declaring the facts about the circumstances and the products by paying the stipulated sum ,
    a premium and not having a motive of making profit from the insurance contract.”</p1>
<br>
<br>
•	Motor Insurance: Motor Insurance can be divided into two group, one is car Four wheeler insurance and other is two wheeler insurance.
<br>
•	Health Insurance: Common types of health insurance includes, individual health insurance, family floater health insurance, comprehensive health insurance and critical illnes insurance.
<br>
•	Travel Insurance: Travel insurance can be broadly grouped into Individual travel policy, Family Travel policy, student travel insurance and senior citizen health insurance.
<br>
•	Home Insurance: Home insurance protects house and its contents in bad time.
<br>
•	Marine Insurance: Marine cargo insurance covers goods, freight, cargo and other interests against loss or damage during transit by rail, road, sea and/or air.

<div>
<a href='{% url "MyAdmin:homepage" %}' class="btn btn-primary" role="button"> Home </a>
</div>
{% endblock %}

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'Common/image.css' %}" />
    <style>
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }

.bg-img {
{% load static %}
  /* The image used */
  background-image: url("{% static '/images/car-insurance.jpg' %}");
  min-height: 480px;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}
</style>
</head>
<body class="body">
<div class="bg-img">
  <!-- Brand -->
  <a class="navbar-brand" href="#"> <h1>GISF Pvt Ltd</h1> </a>
    <br>
    {% if user.is_authenticated %}
    <div>
    <a>Welcome : {{ user.get_username }}  </a>
    <a href='{% url "MyAdmin:logout" %}' class="btn btn-primary" role="button"> Logout </a>
    </div>
    {% else %}
    <a href='{% url "MyAdmin:About" %}' class="btn btn-success" role="button"> AboutUs </a> <br><br>
    <a href='{% url "MyAdmin:clogin" %}' class="btn btn-success" role="button"> Login </a><br><br>
    <a href='{% url "MyAdmin:register" %}' class="btn btn-success" role="button"> Sign-up </a>
    {% endif %}
</div>
</body>
</html>

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/login.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}
* {
  box-sizing: border-box;
}
.bg-img {
{% load static %}
  /* The image used */
  background-image: url("{% static '/images/car-insurance.jpg' %}");
  min-height: 380px;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Add styles to the form container */
.container {
  position: absolute;
  right: 0;
  margin: 20px;
  max-width: 300px;
  padding: 16px;
  background-color: #e5eecc;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.btn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }
</style>
</head>
<body class="body">

<h1>My General Insurance Login</h1>
<div class="bg-img">
  <form  class="container" method="POST">
    {% csrf_token %}
    <h1>Login</h1>
    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <button type="submit" class="btn">Login</button>
  </form>
</div>

  <a href='{% url "MyAdmin:homepage" %}' class="btn btn-primary" role="button"> Home </a>
  <a href='{% url "MyAdmin:register" %}' class="btn btn-primary" role="button">Sign-up</a>
<h2>Pls. Enter your Credentials and login</h2>

</body>
</html>

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/logout.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #00ff80;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }
  header {
  background-color: #666;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

.big {
   padding: 15px 15px 15px 32px;
  font-size: 50px;
  color: #818181;
  display: block;
  padding: 30px;
  text-align: center;
  font-size: 35px;
}

.big span:hover {
  color: green;
        background-color: red;
}

</style>
    <h1 class="big">Successfully Log outed</h1>
</head>
<body class="body">
{% load static %}
{% if user.is_authenticated %}
<div align="right">
<a>Logged User : {{ user.get_username }}  </a>
    <a href='{% url "logout" %}' class="btn btn-primary" role="button"> Logout </a>
{% else %}
    <p>Please log in.</p>
    <a href='{% url "MyAdmin:clogin" %}' class="btn btn-primary" role="button"> Login </a> <br><br>
    <a href='{% url "MyAdmin:homepage" %}' class="btn btn-primary" role="button"> Home </a>
{% endif %}

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
</div>
</body>
</html>

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/mainmenu.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
<link rel="stylesheet" type="text/css" href="{% static 'MyAdmin/mainmenu.css' %}" />
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #00ff80;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 24px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
.body{
      background-color: #e5eecc;
      padding: 25px;
      margin: 20px;
    }
  header {
  background-color: #666;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

.big {
   padding: 15px 15px 15px 32px;
  font-size: 50px;
  color: #818181;
  display: block;
  text-align: center;
  font-size: 35px;
}
.big span:hover {
  color: green;
        background-color: red;
}
</style>
    <h1 class="big">Main Page</h1>
</head>

<body class="body">
{% load static %}
{% if user.is_authenticated %}
<div align="right">
<a>Logged User : {{ user.get_username }}  </a>
    <a href='{% url "MyAdmin:logout" %}' class="btn btn-primary" role="button"> Logout </a>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href='{% url "Masters:ProductsMaster" %}' class="btn btn-primary" role="button">Product</a>
        <a href='{% url "Masters:createAgent" %}' class="btn btn-primary" role="button">Create Agent</a>
        <a href='{% url "Masters:AgentCommission" %}' class="btn btn-primary" role="button">Agent Commission</a>
        <a href='{% url "Masters:VehicleMaster" %}' class="btn btn-primary" role="button">Vehicle Master</a>
        <a href='{% url "Masters:VehicleDepreciation" %}' class="btn btn-primary" role="button">Vehicle Depreciation</a>
        <a href='{% url "Masters:NCBMaster" %}' class="btn btn-primary" role="button">NCB Master</a>
        <a href='{% url "Masters:Claimstatus" %}' class="btn btn-primary" role="button">Claim Status Master</a>
        <a href='{% url "Masters:Surveyormaster" %}' class="btn btn-primary" role="button">Create Surveyor</a>
        <a href='{% url "Masters:ClaimStatusListView" %}' class="btn btn-primary" role="button">Claim Status List</a>


    </div>

    <div id="UWSidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeUWNav()">&times;</a>
        <a href='{% url "UnderWriter:CreateInsured" %}' class="btn btn-primary" role="button">Create Insured</a>
        <a href='{% url "UnderWriter:PolicyCreate" %}' class="btn btn-primary" role="button">Policy Create</a>

    </div>

    <div id="ENDSidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeENDNav()">&times;</a>
        <a href='{% url "UnderWriter:PolicyUpdate" %}' class="btn btn-primary" role="button">Policy Update</a>
        <a href='{% url "UnderWriter:PolicyBillPay" %}' class="btn btn-primary" role="button">Policy Bill Pay</a>
    </div>

        <div id="FINSidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeFINNav()">&times;</a>
        <a href='{% url "MyAdmin:clogin" %}' class="btn btn-primary" role="button">Prodct</a>
    </div>

    <div id="CLMSidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeCLMNav()">&times;</a>
        <a href='{% url "Claim1:RaiseClaim" %}' class="btn btn-primary" role="button">Raise Claim</a>
    </div>

<div class="big">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()"> Masters</span> <br> <br>
    <span style="font-size:30px;cursor:pointer" onclick="openUWNav()"> UnderWriter</span> <br> <br>
    <span style="font-size:30px;cursor:pointer" onclick="openENDNav()"> Endorsement</span> <br> <br>
    <span style="font-size:30px;cursor:pointer" onclick="openCLMNav()">Claims</span> <br> <br>
    <span style="font-size:30px;cursor:pointer" onclick="openFINNav()"> Payments</span> <br>
</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function openUWNav() {
  document.getElementById("UWSidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}
function openENDNav() {
  document.getElementById("ENDSidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function openFINNav() {
  document.getElementById("FINSidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function openCLMNav() {
  document.getElementById("CLMSidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}
function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
function closeUWNav() {
  document.getElementById("UWSidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
function closeENDNav() {
  document.getElementById("ENDSidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
function closeCLMNav() {
  document.getElementById("CLMSidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>

</body>
</html>

GISFproject/GISF/GISFAdmin/templates/GISFAdmin/newuser.html
{% extends 'base.html' %}
<body class="container">
{% block content %}
    <form method="POST">
    	{% csrf_token %}
        {{form.as_p}}
        <button class="submit-row" style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>
</div>

</div>
    If you already have an account <a href='{% url "MyAdmin:clogin" %}' class="btn btn-primary" role="button">Login</a> instead.
{% endblock %}