GISFproject/GISF/GISF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('GISFAdmin/', include('GISFAdmin.urls')),
    path('Masters/', include('Masters.urls')),
    path('UnderWriter/', include('UnderWriter.urls')),
    path('Claims/', include('Claims.urls'))
]

GISFproject/GISF/GISFAdmin/urls.py
from django.urls import path

from .views import NewUserCreate, homepage, about, loginView, logout_view, register, mainmenu

app_name = 'MyAdmin'

urlpatterns = [
    path('registration/', NewUserCreate, name="NewUserCreate"),
    path('', homepage, name='homepage'),
    path('About/', about, name='About'),
    path('clogin/', loginView, name='clogin'),
    path('log-out/', logout_view, name='logout'),
    path("Newregister/", register, name="register"),
    path('mainmenu/', mainmenu, name='mainmenu'),
     ]

GISFproject/GISF/GISFAdmin/models.py
from django.db import models

# Create your models here.


class Users(models.Model):
    username = models.CharField(max_length=120)
    password = models.CharField(max_length=500)

    class Meta:
        db_table = 'Users'

GISFproject/GISF/GISFAdmin/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

from .PasswordManage import decrypt, encrypt
# from .forms import Userform
from .models import Users


# Create your views here.
def NewUserCreate(request):
    password = request.POST.get('pwd')
    username = request.POST.get('uid')
    if request.method == "POST":
        encr = encrypt(password,username)
        Users.objects.create(username=username, password=encr)
        dec = decrypt(encr, username)

    return render(request,'GISFAdminGISFAdmin/Registration.html')


def register(request):
    form = UserCreationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request = request,
                          template_name = "GISFAdmin/newuser.html",
                          context={"form":form})

    form = UserCreationForm
    return render(request = request,
                  template_name = "GISFAdmin/newuser.html",
                  context={"form":form})


def loginView(request):
    if request.method == 'GET':
        return render(request, 'GISFAdmin/login.html', {})
    else:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None :
            login(request, user)
            #return redirect('mainmenu/')
            return render(request, 'GISFAdmin/mainmenu.html', {})
        else:
            return render(request, 'GISFAdmin/login.html', {})


def logout_view(request):
    logout(request)
    return render(request, 'GISFAdmin/logout.html')


def homepage(request):
    return render(request, 'GISFAdmin/home.html')


def about(request):
    return render(request,'GISFAdmin/about.html')


def mainmenu(request):
    return render(request, 'GISFAdmin/mainmenu.html')

GISFproject/GISF/GISFAdmin/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <style>
   {% block style %}
{% endblock %}
    </style>
<head class="container">
{% load static %}
    {% block title %}
{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'GISFAdmin/mainmenu.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Common/bg-frames.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Common/fieldProperties.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Common/image.css' %}" />
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.js'%}"></script>

</head>
    <div class="row">
        <div class="col">
<img class="imgSqrWithBorder" src="{% static 'images/car-insurance.jpg' %}" alt="Car">
    <h2>G I S F</h2>
    {% if user.is_authenticated %}
            </div>
        <div class="col">
    <h1>GISF Solutions</h1>
        </div>
        <div>

<div align="right">
<a>Logged User : {{ user.get_username }}  </a>
    <a href='{% url "MyAdmin:logout" %}' class="btn btn-primary" role="button"> Logout </a>
    <a href='{% url "MyAdmin:mainmenu" %}' class="btn btn-primary" role="button"> MainMenu </a>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}
        </div>
</div>
</div>
   <body class="div1">

    <div class="rcorners1">
   {% block formname %}
    {% endblock %}
    <div class="rcorners1">
    <div class="rcorners2" >
    {% block content %}
     {% endblock %}
    </div>
    </div>

        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>
</html>